auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2026-02-04
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /var/lib/loki/tsdb-index
    cache_location: /var/lib/loki/tsdb-cache
    cache_ttl: 24h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

  retention_period: 744h
  retention_stream:
    - selector: '{app="nginx"}'
      priority: 1
      period: 720h
    - selector: '{app="mysql"}'
      priority: 1
      period: 720h
    - selector: '{app="php-fpm"}'
      priority: 1
      period: 336h

compactor:
  working_directory: /var/lib/loki/compactor
  retention_enabled: true
  compaction_interval: 10m

ruler:
  alertmanager_url: http://localhost:9093
  enable_api: true
  rule_path: /var/lib/loki/rules-temp

analytics:
  reporting_enabled: false
