server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "system"
          __path__: /var/log/syslog

  - job_name: nginx
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "nginx"
          app: "nginx"
          __path__: /var/log/nginx/access.log

  - job_name: nginx_error
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "nginx_error"
          app: "nginx"
          __path__: /var/log/nginx/error.log

  - job_name: all_logs
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "varlogs"
          __path__: /var/log/*.log
